underlay: udp
port: 1299
introducer_address: 192.168.0.4
introducer_port: 1099
name_id_assignment_protocol: none
name_id_value_self_assigned: 1102
numerical_id_assignment_protocol: none
numerical_id_value_self_assigned: 3456
storage_path: none