underlay: udp
port_assignment_protocol: incremental
port_value_self_assigned: 0
introducer_address: 192.168.0.4
introducer_port: 11099
name_id_assignment_protocol: incremental
name_id_value_self_assigned: 0
numerical_id_assignment_protocol: incremental
numerical_id_value_self_assigned: 0
storage_type: none
storage_path: none